lakion_admin_route:
    resource: "@LakionSyliusCmsBundle/Resources/config/app/routing/admin/route.yml"

lakion_admin_static_content:
    resource: "@LakionSyliusCmsBundle/Resources/config/app/routing/admin/static_content.yml"

