lakion_shop_static_content_show:
    path: /{name}
    methods: [GET]
    defaults:
        _controller: sylius.controller.static_content:showAction
        _sylius:
            template: "@LakionSyliusCms/Shop/StaticContent/show.html.twig"
            repository:
                method: findPublishedOneByName
                arguments: [$name]
